name: Publish

on:
  push:
    tags:
      - v*

jobs:
  setup:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      version: ${{ steps.set_outputs.outputs.version }}

    steps:
      - id: set_outputs
        name: Set outputs
        run: |
          VERSION=${GITHUB_REF#refs/*/v}
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      VERSION: ${{ needs.setup.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Release Draft
        run: |
          touch ./CHANGELOG.md
          echo '### Changelog' >> ./CHANGELOG.md
          echo '--------' >> ./CHANGELOG.md
          cat ./CHANGELOG.md

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: \`@bloom-labs/url\` ${{ env.VERSION }}
          body_path: './CHANGELOG.md'
          draft: true
          prerelease: true
